"""Phase 3 reply-generation injection tests (M-07)."""

from __future__ import annotations

from app.config import Settings
from app.llm.client import BaseLLMClient
from app.models.conversation import Conversation
from app.models.customer import Customer
from app.models.email import Email
from app.services.audit import utcnow
from app.services.knowledge import KnowledgeService
from app.services.qa import QAService
from app.services.replier import UNCONFIRMED_MARKER, ReplierService


class CapturingLLM(BaseLLMClient):
    def __init__(self) -> None:
        self.settings = Settings(llm_provider="mock", llm_retries=0)
        self.system_prompt = ""
        self.called = False

    def chat(self, messages, system_prompt=None, max_tokens=None, temperature=None) -> str:
        self.called = True
        self.system_prompt = system_prompt or ""
        return "Generated by LLM"


def _seed(db):
    customer = Customer(email="c@example.com", created_at=utcnow())
    db.add(customer)
    db.flush()
    conversation = Conversation(
        customer_id=customer.id,
        subject_normalized="question",
        window_end=utcnow(),
        last_activity_at=utcnow(),
        status="open",
    )
    db.add(conversation)
    db.flush()
    email = Email(
        conversation_id=conversation.id,
        message_id="<p3@example.com>",
        subject="Question",
        from_email="c@example.com",
        to_email="bot@example.com",
        body_text="What is the shipping time to Germany?",
        is_inbound=True,
        received_at=utcnow(),
    )
    db.add(email)
    db.commit()
    return email, conversation


def test_qa_hit_returns_stored_answer_without_llm(db, settings) -> None:
    email, conversation = _seed(db)
    pair = QAService(db).create(
        "What is the shipping time to Germany?",
        "Shipping to Germany takes 7-10 business days.",
        "shipping",
    )
    db.commit()
    llm = CapturingLLM()
    result = ReplierService(db, settings, llm).generate(email, conversation)
    assert result == pair.answer
    assert llm.called is False


def test_kb_full_text_and_fallback_marker_injected(db, settings) -> None:
    email, conversation = _seed(db)
    KnowledgeService(db).upload("faq.md", b"# FAQ\nShipping to Germany takes 7-10 business days.")
    db.commit()
    llm = CapturingLLM()
    ReplierService(db, settings, llm).generate(email, conversation)
    assert llm.called is True
    assert "faq.md v1" in llm.system_prompt
    assert "Shipping to Germany takes 7-10 business days." in llm.system_prompt
    assert UNCONFIRMED_MARKER in llm.system_prompt


def test_no_kb_no_qa_still_injects_fallback_marker(db, settings) -> None:
    email, conversation = _seed(db)
    llm = CapturingLLM()
    ReplierService(db, settings, llm).generate(email, conversation)
    assert llm.called is True
    assert UNCONFIRMED_MARKER in llm.system_prompt


def test_compensation_prompt_includes_cap(db, settings) -> None:
    email, conversation = _seed(db)
    llm = CapturingLLM()
    ReplierService(db, settings, llm).generate(
        email, conversation, reply_type="retention_compensation"
    )
    assert "20 USD" in llm.system_prompt


def test_compensation_cap_follows_settings(db) -> None:
    email, conversation = _seed(db)
    custom = Settings(llm_provider="mock", llm_retries=0, compensation_max_usd=35.0)
    llm = CapturingLLM()
    ReplierService(db, custom, llm).generate(
        email, conversation, reply_type="retention_compensation"
    )
    assert "35 USD" in llm.system_prompt
    assert "20 USD" not in llm.system_prompt


def test_reassurance_prompt_used(db, settings) -> None:
    email, conversation = _seed(db)
    llm = CapturingLLM()
    ReplierService(db, settings, llm).generate(email, conversation, reply_type="reassurance")
    assert llm.called is True
    assert "24 hours" in llm.system_prompt
